import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import Container from "@/components/organism/Container";


// const inter = Inter({ subsets: ["latin"] });
const lato =  Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Simple Quicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Container>
          {children}
        </Container>
      </body>
    </html>
  );
}
